"""
Merge all data/class*_words.json files into web/data/words.js for the app.

Output assigns a global the page can read without a server (file:// safe):
    window.TAMIL_WORDS = { "10": [["word", freq], ...], ... };
    window.TAMIL_META  = { classes:[...], generated:"...", counts:{...} };

Usage:  py scripts/build_wordsjs.py
"""
import json, glob, os, datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(ROOT, "data")
OUT = os.path.join(ROOT, "web", "data", "words.js")


def main():
    files = sorted(glob.glob(os.path.join(DATA_DIR, "class*_words.json")))
    all_words = {}
    counts = {}
    for fp in files:
        with open(fp, encoding="utf-8") as f:
            d = json.load(f)
        cls = str(d.get("class") or os.path.basename(fp))
        rows = [[w["w"], w["freq"]] for w in d["words"]]
        all_words[cls] = rows
        counts[cls] = len(rows)
        print(f"class {cls}: {len(rows)} words  (from {os.path.basename(fp)})")

    meta = {
        "classes": sorted(all_words.keys(), key=lambda c: (len(c), c)),
        "generated": datetime.datetime.now().isoformat(timespec="seconds"),
        "counts": counts,
    }

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by scripts/build_wordsjs.py - do not edit by hand.\n")
        f.write("window.TAMIL_WORDS = ")
        json.dump(all_words, f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\n")
        f.write("window.TAMIL_META = ")
        json.dump(meta, f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\n")
    size_kb = os.path.getsize(OUT) / 1024
    print(f"\nWrote {OUT}  ({size_kb:.0f} KB)")


if __name__ == "__main__":
    main()
