"""
Merge all data/class*_ilakkanam.json files into web/data/ilakkanam.js for the app.

Usage:  py scripts/build_ilakkanamjs.py
"""
import json
import glob
import os
import datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(ROOT, "data")
OUT = os.path.join(ROOT, "web", "data", "ilakkanam.js")


def main():
    files = sorted(glob.glob(os.path.join(DATA_DIR, "class*_ilakkanam.json")))
    all_q = {}
    counts = {}
    for fp in files:
        with open(fp, encoding="utf-8") as f:
            d = json.load(f)
        cls = str(d.get("class") or os.path.basename(fp))
        qs = d.get("questions") or []
        all_q[cls] = qs
        counts[cls] = len(qs)
        print(f"class {cls}: {len(qs)} questions  (from {os.path.basename(fp)})")

    meta = {
        "classes": sorted(all_q.keys(), key=lambda c: (len(c), c)),
        "generated": datetime.datetime.now().isoformat(timespec="seconds"),
        "counts": counts,
    }

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by scripts/build_ilakkanamjs.py - do not edit by hand.\n")
        f.write("window.TAMIL_ILAKKANAM = ")
        json.dump(all_q, f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\n")
        f.write("window.TAMIL_ILAKKANAM_META = ")
        json.dump(meta, f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\n")
    size_kb = os.path.getsize(OUT) / 1024
    print(f"\nWrote {OUT}  ({size_kb:.1f} KB)")


if __name__ == "__main__":
    main()
